### ISSUE TITLE
翻訳誤作動

### ISSUE THREAD

**Issue by xokikurumi** [xokikurumi/discord_bot_firezunda#2]
** 不具合対象の機能名(README参照) **
翻訳
** 不具合内容 **
`
[2024/04/06 23:25:13.627508][NEW]6のジェイク編から先が出来てないのだ
[2024-04-06 23:25:13] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\4000.workspace\4300.Python\discordBot\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\4000.workspace\4300.Python\discordBot\main.py", line 60, in on_message
    await message.channel.send(diceLog["text"])
KeyError: 'text'
`
- 数字始まり等一部の翻訳でエラーを出力する
- 何らかの条件で翻訳を起こす場合がある

**Comment by xokikurumi** [comment]
絵文字系削除機能の実装
